### PR TITLE
BRE: translations for br market

### PR DESCRIPTION
**Pull request by natanprog**
Do I need to translate any more files?

### CODE REVIEW

**Comment by natanprog** [comment]
Hi @cheesasaurus 
Thanks for all the amazing scripts 👍

Do I need to add these variables to some other file?

`twcheese.language['months'][0] = 'Jan';
twcheese.language['months'][1] = 'Fev';
twcheese.language['months'][2] = 'Mar';
twcheese.language['months'][3] = 'Abr';
twcheese.language['months'][4] = 'Mai';
twcheese.language['months'][5] = 'Jun';
twcheese.language['months'][6] = 'Jul';
twcheese.language['months'][7] = 'Ago';
twcheese.language['months'][8] = 'Set';
twcheese.language['months'][9] = 'Out';
twcheese.language['months'][10] = 'Nov';
twcheese.language['months'][11] = 'Dez';`

Because in some reports the date does not work correctly

data works
data not works

Can you inform me? all files and places that translations can be added?

I want to translate as much as possible into Brazilian Portuguese

thanks!

**Comment by cheesasaurus** [comment]
Hey Natan,

That forum post is a bit outdated.

Nowadays the TextScraper is the only place to add translations. I though about setting up i18n for displays but never got around to it. https://github.com/cheesasaurus/twcheese/issues/43

The time parsing is handled here:
https://github.com/cheesasaurus/twcheese/blob/develop/src/Scrape/time.js

**Comment by natanprog** [comment]
@cheesasaurus 

The translation I added to the "TextScraper.js" file is in the current format (not the forum format)
Regarding the date, I am not a developer and I do not have the necessary knowledge to correct
the date format on the .BR server is the same format as the .NET server
The only difference that I noticed in the prints above,
is that the abbreviation for March is the same in both languages (English / Portuguese) and different in May

"Mar" == "Mar"
"May" != "Mai"

If it is possible to implement the corrections so that the script is functional on the .BR server
Sorry I can't help with coding (I don't have the necessary knowledge)

thanks

**Comment by cheesasaurus** [comment]
Sure. I don't play anymore but I gave it a shot: https://github.com/cheesasaurus/twcheese/commit/d3ba83866c7ab5842e5aa885738d3b3fb00d97d1

I merged in your changes and deployed a new version.
With any luck it'll start working on .BR

For not being a developer, you did a pretty good job figuring out how to use github. Good stuff 😎

**Pull request merged**
